// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Represents an achievement
 */
export class Achievement {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Gets the achievement ID
     */
    id(): string;

    /**
     * Gets the world address (hex)
     */
    worldAddress(): string;

    /**
     * Gets the namespace
     */
    namespace(): string;

    /**
     * Gets the achievement title
     */
    title(): string;

    /**
     * Gets the achievement description
     */
    description(): string;

    /**
     * Gets the hidden flag
     */
    hidden(): boolean;

    /**
     * Gets the icon URI
     */
    icon(): string;

    /**
     * Gets the points for this achievement
     */
    points(): number;

    /**
     * Creates an achievement from JSON
     */
    static fromJson(json: string): Achievement;

    /**
     * Serializes the achievement to JSON
     */
    toJson(): string;
}