// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Represents an activity
 */
export class Activity {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Gets the activity ID
     */
    id(): string;

    /**
     * Gets the world address (hex)
     */
    worldAddress(): string;

    /**
     * Gets the namespace
     */
    namespace(): string;

    /**
     * Gets the caller address (hex)
     */
    callerAddress(): string;

    /**
     * Gets the session start timestamp
     */
    sessionStart(): bigint;

    /**
     * Gets the session end timestamp
     */
    sessionEnd(): bigint;

    /**
     * Gets the action count
     */
    actionCount(): number;

    /**
     * Gets the updated_at timestamp
     */
    updatedAt(): bigint;

    /**
     * Creates an activity from JSON
     */
    static fromJson(json: string): Activity;

    /**
     * Serializes the activity to JSON
     */
    toJson(): string;
}