// generated by diplomat-tool
import { DojoError } from "./DojoError.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const Activity_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.Activity_destroy(ptr);
});

/**
 * Represents an activity
 */
export class Activity {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("Activity is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            Activity_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    /**
     * Gets the activity ID
     */
    id() {
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.Activity_id(this.ffiValue, write.buffer);

        try {
            return write.readString8();
        }

        finally {
            write.free();
        }
    }

    /**
     * Gets the world address (hex)
     */
    worldAddress() {
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.Activity_world_address(this.ffiValue, write.buffer);

        try {
            return write.readString8();
        }

        finally {
            write.free();
        }
    }

    /**
     * Gets the namespace
     */
    namespace() {
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.Activity_namespace(this.ffiValue, write.buffer);

        try {
            return write.readString8();
        }

        finally {
            write.free();
        }
    }

    /**
     * Gets the caller address (hex)
     */
    callerAddress() {
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.Activity_caller_address(this.ffiValue, write.buffer);

        try {
            return write.readString8();
        }

        finally {
            write.free();
        }
    }

    /**
     * Gets the session start timestamp
     */
    sessionStart() {

        const result = wasm.Activity_session_start(this.ffiValue);

        try {
            return result;
        }

        finally {
        }
    }

    /**
     * Gets the session end timestamp
     */
    sessionEnd() {

        const result = wasm.Activity_session_end(this.ffiValue);

        try {
            return result;
        }

        finally {
        }
    }

    /**
     * Gets the action count
     */
    actionCount() {

        const result = wasm.Activity_action_count(this.ffiValue);

        try {
            return result;
        }

        finally {
        }
    }

    /**
     * Gets the updated_at timestamp
     */
    updatedAt() {

        const result = wasm.Activity_updated_at(this.ffiValue);

        try {
            return result;
        }

        finally {
        }
    }

    /**
     * Creates an activity from JSON
     */
    static fromJson(json) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const jsonSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, json)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Activity_from_json(diplomatReceive.buffer, jsonSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new DojoError(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
                throw new globalThis.Error('DojoError: ' + cause.toString(), { cause });
            }
            return new Activity(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * Serializes the activity to JSON
     */
    toJson() {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);

        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);


        const result = wasm.Activity_to_json(diplomatReceive.buffer, this.ffiValue, write.buffer);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new DojoError(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
                throw new globalThis.Error('DojoError: ' + cause.toString(), { cause });
            }
            return write.readString8();
        }

        finally {
            diplomatReceive.free();
            write.free();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}