// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Represents an aggregation entry
 */
export class AggregationEntry {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Gets the aggregation ID
     */
    id(): string;

    /**
     * Gets the aggregator ID
     */
    aggregatorId(): string;

    /**
     * Gets the entity ID
     */
    entityId(): string;

    /**
     * Gets the model ID
     */
    modelId(): string;

    /**
     * Gets the aggregation value
     */
    value(): string;

    /**
     * Gets the display value
     */
    displayValue(): string;

    /**
     * Gets the position
     */
    position(): bigint;

    /**
     * Gets the created_at timestamp
     */
    createdAt(): bigint;

    /**
     * Gets the updated_at timestamp
     */
    updatedAt(): bigint;

    /**
     * Creates an aggregation entry from JSON
     */
    static fromJson(json: string): AggregationEntry;

    /**
     * Serializes the aggregation entry to JSON
     */
    toJson(): string;
}