// generated by diplomat-tool
import { DojoError } from "./DojoError.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const AggregationEntry_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.AggregationEntry_destroy(ptr);
});

/**
 * Represents an aggregation entry
 */
export class AggregationEntry {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("AggregationEntry is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            AggregationEntry_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    /**
     * Gets the aggregation ID
     */
    id() {
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.AggregationEntry_id(this.ffiValue, write.buffer);

        try {
            return write.readString8();
        }

        finally {
            write.free();
        }
    }

    /**
     * Gets the aggregator ID
     */
    aggregatorId() {
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.AggregationEntry_aggregator_id(this.ffiValue, write.buffer);

        try {
            return write.readString8();
        }

        finally {
            write.free();
        }
    }

    /**
     * Gets the entity ID
     */
    entityId() {
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.AggregationEntry_entity_id(this.ffiValue, write.buffer);

        try {
            return write.readString8();
        }

        finally {
            write.free();
        }
    }

    /**
     * Gets the model ID
     */
    modelId() {
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.AggregationEntry_model_id(this.ffiValue, write.buffer);

        try {
            return write.readString8();
        }

        finally {
            write.free();
        }
    }

    /**
     * Gets the aggregation value
     */
    value() {
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.AggregationEntry_value(this.ffiValue, write.buffer);

        try {
            return write.readString8();
        }

        finally {
            write.free();
        }
    }

    /**
     * Gets the display value
     */
    displayValue() {
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.AggregationEntry_display_value(this.ffiValue, write.buffer);

        try {
            return write.readString8();
        }

        finally {
            write.free();
        }
    }

    /**
     * Gets the position
     */
    position() {

        const result = wasm.AggregationEntry_position(this.ffiValue);

        try {
            return result;
        }

        finally {
        }
    }

    /**
     * Gets the created_at timestamp
     */
    createdAt() {

        const result = wasm.AggregationEntry_created_at(this.ffiValue);

        try {
            return result;
        }

        finally {
        }
    }

    /**
     * Gets the updated_at timestamp
     */
    updatedAt() {

        const result = wasm.AggregationEntry_updated_at(this.ffiValue);

        try {
            return result;
        }

        finally {
        }
    }

    /**
     * Creates an aggregation entry from JSON
     */
    static fromJson(json) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const jsonSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, json)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.AggregationEntry_from_json(diplomatReceive.buffer, jsonSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new DojoError(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
                throw new globalThis.Error('DojoError: ' + cause.toString(), { cause });
            }
            return new AggregationEntry(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * Serializes the aggregation entry to JSON
     */
    toJson() {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);

        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);


        const result = wasm.AggregationEntry_to_json(diplomatReceive.buffer, this.ffiValue, write.buffer);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new DojoError(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
                throw new globalThis.Error('DojoError: ' + cause.toString(), { cause });
            }
            return write.readString8();
        }

        finally {
            diplomatReceive.free();
            write.free();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}