// generated by diplomat-tool
import type { BlockTag } from "./BlockTag"
import type { FieldElement } from "./FieldElement"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Block identifier (hash, number, or tag)
 */
export class BlockId {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Creates a BlockId from a block hash
     */
    static fromHash(hash: FieldElement): BlockId;

    /**
     * Creates a BlockId from a block number
     */
    static fromNumber(number: bigint): BlockId;

    /**
     * Creates a BlockId from a block tag
     */
    static fromTag(tag: BlockTag): BlockId;
}