// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



/**
 * Block tag for identifying specific blocks
 */
export class BlockTag {
    #value = undefined;

    static #values = new Map([
        ["Latest", 0],
        ["PreConfirmed", 1]
    ]);

    static getAllEntries() {
        return BlockTag.#values.entries();
    }

    #internalConstructor(value) {
        if (arguments.length > 1 && arguments[0] === diplomatRuntime.internalConstructor) {
            // We pass in two internalConstructor arguments to create *new*
            // instances of this type, otherwise the enums are treated as singletons.
            if (arguments[1] === diplomatRuntime.internalConstructor ) {
                this.#value = arguments[2];
                return this;
            }
            return BlockTag.#objectValues[arguments[1]];
        }

        if (value instanceof BlockTag) {
            return value;
        }

        let intVal = BlockTag.#values.get(value);

        // Nullish check, checks for null or undefined
        if (intVal != null) {
            return BlockTag.#objectValues[intVal];
        }

        throw TypeError(value + " is not a BlockTag and does not correspond to any of its enumerator values.");
    }

    /** @internal */
    static fromValue(value) {
        return new BlockTag(value);
    }

    get value(){
        return [...BlockTag.#values.keys()][this.#value];
    }

    /** @internal */
    get ffiValue(){
        return this.#value;
    }
    static #objectValues = [
        new BlockTag(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 0),
        new BlockTag(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 1),
    ];

    static Latest = BlockTag.#objectValues[0];
    static PreConfirmed = BlockTag.#objectValues[1];


    constructor(value) {
        return this.#internalConstructor(...arguments)
    }
}