// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Block tag for identifying specific blocks
 */
export class BlockTag {

    /** @internal */
    static fromValue(value: BlockTag | string): BlockTag;

    get value(): string;

    /** @internal */
    get ffiValue(): number;

    static Latest : BlockTag;
    static PreConfirmed : BlockTag;


    constructor(value: BlockTag | string );
}