// generated by diplomat-tool
import { DojoError } from "./DojoError.mjs"
import { FieldElement } from "./FieldElement.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const Call_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.Call_destroy(ptr);
});

/**
 * Represents a Starknet call
 */
export class Call {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("Call is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            Call_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    /**
     * Creates a new Call
     */
    static new_(to, selector) {

        const result = wasm.Call_new(to.ffiValue, selector.ffiValue);

        try {
            return new Call(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
        }
    }

    /**
     * Adds a field element to the calldata
     */
    pushCalldata(felt) {
    wasm.Call_push_calldata(this.ffiValue, felt.ffiValue);

        try {}

        finally {
        }
    }

    /**
     * Creates a call from selector name
     */
    static newFromSelectorName(to, selectorName) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const selectorNameSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, selectorName)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Call_new_from_selector_name(diplomatReceive.buffer, to.ffiValue, selectorNameSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new DojoError(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
                throw new globalThis.Error('DojoError: ' + cause.toString(), { cause });
            }
            return new Call(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}