// generated by diplomat-tool
import type { Call } from "./Call"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * List of calls for batch transactions
 */
export class CallList {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Creates a new empty call list
     */
    static new_(): CallList;

    /**
     * Adds a call to the list
     */
    addCall(call: Call): void;

    /**
     * Returns the number of calls in the list
     */
    len(): number;
}