// generated by diplomat-tool
import { Call } from "./Call.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const CallList_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.CallList_destroy(ptr);
});

/**
 * List of calls for batch transactions
 */
export class CallList {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("CallList is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            CallList_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    /**
     * Creates a new empty call list
     */
    static new_() {

        const result = wasm.CallList_new();

        try {
            return new CallList(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
        }
    }

    /**
     * Adds a call to the list
     */
    addCall(call) {
    wasm.CallList_add_call(this.ffiValue, call.ffiValue);

        try {}

        finally {
        }
    }

    /**
     * Returns the number of calls in the list
     */
    len() {

        const result = wasm.CallList_len(this.ffiValue);

        try {
            return result;
        }

        finally {
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}