// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { FieldElement } from "./FieldElement"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Represents a Starknet call
 */
export class Call {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Creates a new Call
     */
    static new_(to: FieldElement, selector: FieldElement): Call;

    /**
     * Adds a field element to the calldata
     */
    pushCalldata(felt: FieldElement): void;

    /**
     * Creates a call from selector name
     */
    static newFromSelectorName(to: FieldElement, selectorName: string): Call;
}