// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



/**
 * Type of call in a transaction
 */
export class CallType {
    #value = undefined;

    static #values = new Map([
        ["Execute", 0],
        ["ExecuteFromOutside", 1]
    ]);

    static getAllEntries() {
        return CallType.#values.entries();
    }

    #internalConstructor(value) {
        if (arguments.length > 1 && arguments[0] === diplomatRuntime.internalConstructor) {
            // We pass in two internalConstructor arguments to create *new*
            // instances of this type, otherwise the enums are treated as singletons.
            if (arguments[1] === diplomatRuntime.internalConstructor ) {
                this.#value = arguments[2];
                return this;
            }
            return CallType.#objectValues[arguments[1]];
        }

        if (value instanceof CallType) {
            return value;
        }

        let intVal = CallType.#values.get(value);

        // Nullish check, checks for null or undefined
        if (intVal != null) {
            return CallType.#objectValues[intVal];
        }

        throw TypeError(value + " is not a CallType and does not correspond to any of its enumerator values.");
    }

    /** @internal */
    static fromValue(value) {
        return new CallType(value);
    }

    get value(){
        return [...CallType.#values.keys()][this.#value];
    }

    /** @internal */
    get ffiValue(){
        return this.#value;
    }
    static #objectValues = [
        new CallType(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 0),
        new CallType(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 1),
    ];

    static Execute = CallType.#objectValues[0];
    static ExecuteFromOutside = CallType.#objectValues[1];


    constructor(value) {
        return this.#internalConstructor(...arguments)
    }
}