// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Type of call in a transaction
 */
export class CallType {

    /** @internal */
    static fromValue(value: CallType | string): CallType;

    get value(): string;

    /** @internal */
    get ffiValue(): number;

    static Execute : CallType;
    static ExecuteFromOutside : CallType;


    constructor(value: CallType | string );
}