// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Query clause for filtering entities
 */
export class Clause {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();

}