// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Comparison operators for member clauses
 */
export class ComparisonOperator {

    /** @internal */
    static fromValue(value: ComparisonOperator | string): ComparisonOperator;

    get value(): string;

    /** @internal */
    get ffiValue(): number;

    static Eq : ComparisonOperator;
    static Neq : ComparisonOperator;
    static Gt : ComparisonOperator;
    static Gte : ComparisonOperator;
    static Lt : ComparisonOperator;
    static Lte : ComparisonOperator;
    static In : ComparisonOperator;
    static NotIn : ComparisonOperator;
    static Contains : ComparisonOperator;
    static ContainsAll : ComparisonOperator;
    static ContainsAny : ComparisonOperator;
    static ArrayLengthEq : ComparisonOperator;
    static ArrayLengthGt : ComparisonOperator;
    static ArrayLengthLt : ComparisonOperator;


    constructor(value: ComparisonOperator | string );
}