// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Represents a contract
 */
export class Contract {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Gets the contract address (hex)
     */
    contractAddress(): string;

    /**
     * Gets the contract type as string
     */
    contractType(): string;

    /**
     * Gets the head block number (if any)
     */
    head(): bigint;

    /**
     * Gets the TPS (transactions per second) if available
     */
    tps(): bigint;

    /**
     * Gets the created_at timestamp
     */
    createdAt(): bigint;

    /**
     * Gets the updated_at timestamp
     */
    updatedAt(): bigint;

    /**
     * Creates a contract from JSON
     */
    static fromJson(json: string): Contract;

    /**
     * Serializes the contract to JSON
     */
    toJson(): string;
}