// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



/**
 * Type of contract
 */
export class ContractType {
    #value = undefined;

    static #values = new Map([
        ["World", 0],
        ["Erc20", 1],
        ["Erc721", 2],
        ["Erc1155", 3],
        ["Udc", 4],
        ["Other", 5]
    ]);

    static getAllEntries() {
        return ContractType.#values.entries();
    }

    #internalConstructor(value) {
        if (arguments.length > 1 && arguments[0] === diplomatRuntime.internalConstructor) {
            // We pass in two internalConstructor arguments to create *new*
            // instances of this type, otherwise the enums are treated as singletons.
            if (arguments[1] === diplomatRuntime.internalConstructor ) {
                this.#value = arguments[2];
                return this;
            }
            return ContractType.#objectValues[arguments[1]];
        }

        if (value instanceof ContractType) {
            return value;
        }

        let intVal = ContractType.#values.get(value);

        // Nullish check, checks for null or undefined
        if (intVal != null) {
            return ContractType.#objectValues[intVal];
        }

        throw TypeError(value + " is not a ContractType and does not correspond to any of its enumerator values.");
    }

    /** @internal */
    static fromValue(value) {
        return new ContractType(value);
    }

    get value(){
        return [...ContractType.#values.keys()][this.#value];
    }

    /** @internal */
    get ffiValue(){
        return this.#value;
    }
    static #objectValues = [
        new ContractType(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 0),
        new ContractType(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 1),
        new ContractType(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 2),
        new ContractType(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 3),
        new ContractType(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 4),
        new ContractType(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 5),
    ];

    static World = ContractType.#objectValues[0];
    static Erc20 = ContractType.#objectValues[1];
    static Erc721 = ContractType.#objectValues[2];
    static Erc1155 = ContractType.#objectValues[3];
    static Udc = ContractType.#objectValues[4];
    static Other = ContractType.#objectValues[5];


    constructor(value) {
        return this.#internalConstructor(...arguments)
    }
}