// generated by diplomat-tool
import { DojoError } from "./DojoError.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const Contract_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.Contract_destroy(ptr);
});

/**
 * Represents a contract
 */
export class Contract {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("Contract is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            Contract_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    /**
     * Gets the contract address (hex)
     */
    contractAddress() {
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.Contract_contract_address(this.ffiValue, write.buffer);

        try {
            return write.readString8();
        }

        finally {
            write.free();
        }
    }

    /**
     * Gets the contract type as string
     */
    contractType() {
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.Contract_contract_type(this.ffiValue, write.buffer);

        try {
            return write.readString8();
        }

        finally {
            write.free();
        }
    }

    /**
     * Gets the head block number (if any)
     */
    head() {

        const result = wasm.Contract_head(this.ffiValue);

        try {
            return result;
        }

        finally {
        }
    }

    /**
     * Gets the TPS (transactions per second) if available
     */
    tps() {

        const result = wasm.Contract_tps(this.ffiValue);

        try {
            return result;
        }

        finally {
        }
    }

    /**
     * Gets the created_at timestamp
     */
    createdAt() {

        const result = wasm.Contract_created_at(this.ffiValue);

        try {
            return result;
        }

        finally {
        }
    }

    /**
     * Gets the updated_at timestamp
     */
    updatedAt() {

        const result = wasm.Contract_updated_at(this.ffiValue);

        try {
            return result;
        }

        finally {
        }
    }

    /**
     * Creates a contract from JSON
     */
    static fromJson(json) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const jsonSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, json)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Contract_from_json(diplomatReceive.buffer, jsonSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new DojoError(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
                throw new globalThis.Error('DojoError: ' + cause.toString(), { cause });
            }
            return new Contract(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * Serializes the contract to JSON
     */
    toJson() {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);

        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);


        const result = wasm.Contract_to_json(diplomatReceive.buffer, this.ffiValue, write.buffer);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new DojoError(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
                throw new globalThis.Error('DojoError: ' + cause.toString(), { cause });
            }
            return write.readString8();
        }

        finally {
            diplomatReceive.free();
            write.free();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}