// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Type of contract
 */
export class ContractType {

    /** @internal */
    static fromValue(value: ContractType | string): ContractType;

    get value(): string;

    /** @internal */
    get ffiValue(): number;

    static World : ContractType;
    static Erc20 : ContractType;
    static Erc721 : ContractType;
    static Erc1155 : ContractType;
    static Udc : ContractType;
    static Other : ContractType;


    constructor(value: ContractType | string );
}