// generated by diplomat-tool
import type { ErrorType } from "./ErrorType"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Error types for Dojo operations
 */
export class DojoError {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    static new_(errorType: ErrorType, message: string): DojoError;

    /**
     * Gets the error message
     */
    message(): string;

    /**
     * Gets the error type
     */
    errorType(): ErrorType;
}