// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const EntityQuery_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.EntityQuery_destroy(ptr);
});

/**
 * Entity query for retrieving entities from Torii
 */
export class EntityQuery {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("EntityQuery is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            EntityQuery_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    /**
     * Creates a new entity query
     */
    static new_() {

        const result = wasm.EntityQuery_new();

        try {
            return new EntityQuery(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
        }
    }

    /**
     * Sets the limit for the query
     */
    setLimit(limit) {
    wasm.EntityQuery_set_limit(this.ffiValue, limit);

        try {}

        finally {
        }
    }

    /**
     * Sets the offset for the query
     */
    setOffset(offset) {
    wasm.EntityQuery_set_offset(this.ffiValue, offset);

        try {}

        finally {
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}