// generated by diplomat-tool
import { DojoError } from "./DojoError.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const Entity_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.Entity_destroy(ptr);
});

/**
 * Represents a Dojo entity
 */
export class Entity {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("Entity is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            Entity_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    /**
     * Gets the hashed keys (hex)
     */
    hashedKeys() {
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.Entity_hashed_keys(this.ffiValue, write.buffer);

        try {
            return write.readString8();
        }

        finally {
            write.free();
        }
    }

    /**
     * Gets the number of models in this entity
     */
    modelsCount() {

        const result = wasm.Entity_models_count(this.ffiValue);

        try {
            return result;
        }

        finally {
        }
    }

    /**
     * Gets the created_at timestamp
     */
    createdAt() {

        const result = wasm.Entity_created_at(this.ffiValue);

        try {
            return result;
        }

        finally {
        }
    }

    /**
     * Gets the updated_at timestamp
     */
    updatedAt() {

        const result = wasm.Entity_updated_at(this.ffiValue);

        try {
            return result;
        }

        finally {
        }
    }

    /**
     * Gets the executed_at timestamp
     */
    executedAt() {

        const result = wasm.Entity_executed_at(this.ffiValue);

        try {
            return result;
        }

        finally {
        }
    }

    /**
     * Creates a new entity from JSON
     */
    static fromJson(json) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const jsonSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, json)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Entity_from_json(diplomatReceive.buffer, jsonSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new DojoError(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
                throw new globalThis.Error('DojoError: ' + cause.toString(), { cause });
            }
            return new Entity(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * Serializes the entity to JSON
     */
    toJson() {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);

        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);


        const result = wasm.Entity_to_json(diplomatReceive.buffer, this.ffiValue, write.buffer);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new DojoError(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
                throw new globalThis.Error('DojoError: ' + cause.toString(), { cause });
            }
            return write.readString8();
        }

        finally {
            diplomatReceive.free();
            write.free();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}