// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Represents a Dojo entity
 */
export class Entity {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Gets the hashed keys (hex)
     */
    hashedKeys(): string;

    /**
     * Gets the number of models in this entity
     */
    modelsCount(): number;

    /**
     * Gets the created_at timestamp
     */
    createdAt(): bigint;

    /**
     * Gets the updated_at timestamp
     */
    updatedAt(): bigint;

    /**
     * Gets the executed_at timestamp
     */
    executedAt(): bigint;

    /**
     * Creates a new entity from JSON
     */
    static fromJson(json: string): Entity;

    /**
     * Serializes the entity to JSON
     */
    toJson(): string;
}