// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Entity query for retrieving entities from Torii
 */
export class EntityQuery {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Creates a new entity query
     */
    static new_(): EntityQuery;

    /**
     * Sets the limit for the query
     */
    setLimit(limit: number): void;

    /**
     * Sets the offset for the query
     */
    setOffset(offset: number): void;
}