// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Represents a Dojo enum
 */
export class Enum {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Gets the enum name
     */
    name(): string;

    /**
     * Gets the current option (selected variant) index
     */
    option(): number;

    /**
     * Gets the number of options (variants)
     */
    optionsCount(): number;

    /**
     * Creates a new enum from JSON schema
     */
    static fromJson(json: string): Enum;

    /**
     * Serializes the enum to JSON
     */
    toJson(): string;
}