// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class ErrorType {

    /** @internal */
    static fromValue(value: ErrorType | string): ErrorType;

    get value(): string;

    /** @internal */
    get ffiValue(): number;

    static ClientError : ErrorType;
    static ParseError : ErrorType;
    static EntityError : ErrorType;
    static QueryError : ErrorType;
    static SubscriptionError : ErrorType;
    static TransactionError : ErrorType;
    static AccountError : ErrorType;
    static SigningError : ErrorType;
    static ProviderError : ErrorType;
    static StorageError : ErrorType;
    static ControllerError : ErrorType;
    static InvalidInput : ErrorType;
    static RuntimeError : ErrorType;


    constructor(value: ErrorType | string );
}