// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Represents a Dojo event message
 */
export class Event {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Gets the keys as JSON array string
     */
    keys(): string;

    /**
     * Gets the data as JSON array string
     */
    data(): string;

    /**
     * Gets the transaction hash (hex)
     */
    transactionHash(): string;

    /**
     * Creates an event from JSON
     */
    static fromJson(json: string): Event;

    /**
     * Serializes the event to JSON
     */
    toJson(): string;
}