// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Represents a Starknet field element (Felt)
 */
export class FieldElement {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Creates a new FieldElement from a hexadecimal string
     */
    static newFromHex(hex: string): FieldElement;

    /**
     * Creates a new FieldElement from big-endian bytes
     */
    static newFromBytes(bytes: Array<number>): FieldElement;

    /**
     * Returns the field element as a hexadecimal string
     */
    toHex(): string;

    /**
     * Returns the field element as bytes (big-endian)
     */
    toBytes(result: Array<number>): void;
}