// generated by diplomat-tool
import { DojoError } from "./DojoError.mjs"
import { FieldElement } from "./FieldElement.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const KeysClause_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.KeysClause_destroy(ptr);
});

/**
 * Keys clause for filtering by entity keys
 */
export class KeysClause {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("KeysClause is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            KeysClause_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    /**
     * Creates a new keys clause
     */
    static new_() {

        const result = wasm.KeysClause_new();

        try {
            return new KeysClause(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
        }
    }

    /**
     * Adds a key to filter by
     */
    addKey(key) {
    wasm.KeysClause_add_key(this.ffiValue, key.ffiValue);

        try {}

        finally {
        }
    }

    /**
     * Adds a model to filter by
     */
    addModel(model) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const modelSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, model)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.KeysClause_add_model(diplomatReceive.buffer, this.ffiValue, modelSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new DojoError(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
                throw new globalThis.Error('DojoError: ' + cause.toString(), { cause });
            }
        }

        finally {
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}