// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { FieldElement } from "./FieldElement"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Keys clause for filtering by entity keys
 */
export class KeysClause {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Creates a new keys clause
     */
    static new_(): KeysClause;

    /**
     * Adds a key to filter by
     */
    addKey(key: FieldElement): void;

    /**
     * Adds a model to filter by
     */
    addModel(model: string): void;
}