// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



/**
 * Logical operator for combining clauses
 */
export class LogicalOperator {
    #value = undefined;

    static #values = new Map([
        ["And", 0],
        ["Or", 1]
    ]);

    static getAllEntries() {
        return LogicalOperator.#values.entries();
    }

    #internalConstructor(value) {
        if (arguments.length > 1 && arguments[0] === diplomatRuntime.internalConstructor) {
            // We pass in two internalConstructor arguments to create *new*
            // instances of this type, otherwise the enums are treated as singletons.
            if (arguments[1] === diplomatRuntime.internalConstructor ) {
                this.#value = arguments[2];
                return this;
            }
            return LogicalOperator.#objectValues[arguments[1]];
        }

        if (value instanceof LogicalOperator) {
            return value;
        }

        let intVal = LogicalOperator.#values.get(value);

        // Nullish check, checks for null or undefined
        if (intVal != null) {
            return LogicalOperator.#objectValues[intVal];
        }

        throw TypeError(value + " is not a LogicalOperator and does not correspond to any of its enumerator values.");
    }

    /** @internal */
    static fromValue(value) {
        return new LogicalOperator(value);
    }

    get value(){
        return [...LogicalOperator.#values.keys()][this.#value];
    }

    /** @internal */
    get ffiValue(){
        return this.#value;
    }
    static #objectValues = [
        new LogicalOperator(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 0),
        new LogicalOperator(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 1),
    ];

    static And = LogicalOperator.#objectValues[0];
    static Or = LogicalOperator.#objectValues[1];


    constructor(value) {
        return this.#internalConstructor(...arguments)
    }
}