// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Logical operator for combining clauses
 */
export class LogicalOperator {

    /** @internal */
    static fromValue(value: LogicalOperator | string): LogicalOperator;

    get value(): string;

    /** @internal */
    get ffiValue(): number;

    static And : LogicalOperator;
    static Or : LogicalOperator;


    constructor(value: LogicalOperator | string );
}