// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Represents a Dojo struct member (field)
 */
export class Member {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Gets the member name
     */
    name(): string;

    /**
     * Returns true if this member is a key
     */
    isKey(): boolean;
}