// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Model query for retrieving model definitions
 */
export class ModelQuery {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Creates a new model query
     */
    static new_(): ModelQuery;

    /**
     * Adds a model name to query
     */
    addModel(modelName: string): void;
}