// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Represents a Dojo model
 */
export class Model {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Gets the model name
     */
    name(): string;

    /**
     * Gets the model namespace
     */
    namespace(): string;

    /**
     * Gets the model selector (hex)
     */
    selector(): string;

    /**
     * Gets the model class hash (hex)
     */
    classHash(): string;

    /**
     * Gets the model contract address (hex)
     */
    contractAddress(): string;

    /**
     * Gets the packed size
     */
    packedSize(): number;

    /**
     * Gets the unpacked size
     */
    unpackedSize(): number;

    /**
     * Returns true if the model uses legacy store
     */
    useLegacyStore(): boolean;

    /**
     * Creates a new model from JSON
     */
    static fromJson(json: string): Model;

    /**
     * Serializes the model to JSON
     */
    toJson(): string;
}