// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { OrderDirection } from "./OrderDirection"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Ordering specification for query results
 */
export class OrderBy {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Creates a new OrderBy specification
     */
    static new_(field: string, direction: OrderDirection): OrderBy;
}