// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Direction for ordering results
 */
export class OrderDirection {

    /** @internal */
    static fromValue(value: OrderDirection | string): OrderDirection;

    get value(): string;

    /** @internal */
    get ffiValue(): number;

    static Asc : OrderDirection;
    static Desc : OrderDirection;


    constructor(value: OrderDirection | string );
}