// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



/**
 * Direction for ordering results
 */
export class OrderDirection {
    #value = undefined;

    static #values = new Map([
        ["Asc", 0],
        ["Desc", 1]
    ]);

    static getAllEntries() {
        return OrderDirection.#values.entries();
    }

    #internalConstructor(value) {
        if (arguments.length > 1 && arguments[0] === diplomatRuntime.internalConstructor) {
            // We pass in two internalConstructor arguments to create *new*
            // instances of this type, otherwise the enums are treated as singletons.
            if (arguments[1] === diplomatRuntime.internalConstructor ) {
                this.#value = arguments[2];
                return this;
            }
            return OrderDirection.#objectValues[arguments[1]];
        }

        if (value instanceof OrderDirection) {
            return value;
        }

        let intVal = OrderDirection.#values.get(value);

        // Nullish check, checks for null or undefined
        if (intVal != null) {
            return OrderDirection.#objectValues[intVal];
        }

        throw TypeError(value + " is not a OrderDirection and does not correspond to any of its enumerator values.");
    }

    /** @internal */
    static fromValue(value) {
        return new OrderDirection(value);
    }

    get value(){
        return [...OrderDirection.#values.keys()][this.#value];
    }

    /** @internal */
    get ffiValue(){
        return this.#value;
    }
    static #objectValues = [
        new OrderDirection(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 0),
        new OrderDirection(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 1),
    ];

    static Asc = OrderDirection.#objectValues[0];
    static Desc = OrderDirection.#objectValues[1];


    constructor(value) {
        return this.#internalConstructor(...arguments)
    }
}