// generated by diplomat-tool
import { DojoError } from "./DojoError.mjs"
import { OrderBy } from "./OrderBy.mjs"
import { PaginationDirection } from "./PaginationDirection.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const Pagination_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.Pagination_destroy(ptr);
});

/**
 * Pagination configuration for queries
 */
export class Pagination {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("Pagination is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            Pagination_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    /**
     * Creates a new Pagination with default values
     */
    static new_() {

        const result = wasm.Pagination_new();

        try {
            return new Pagination(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
        }
    }

    /**
     * Sets the cursor for pagination
     */
    setCursor(cursor) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const cursorSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, cursor)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Pagination_set_cursor(diplomatReceive.buffer, this.ffiValue, cursorSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new DojoError(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
                throw new globalThis.Error('DojoError: ' + cause.toString(), { cause });
            }
        }

        finally {
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * Sets the limit for pagination
     */
    setLimit(limit) {
    wasm.Pagination_set_limit(this.ffiValue, limit);

        try {}

        finally {
        }
    }

    /**
     * Sets the direction for pagination
     */
    setDirection(direction) {
    wasm.Pagination_set_direction(this.ffiValue, direction.ffiValue);

        try {}

        finally {
        }
    }

    /**
     * Adds an ordering specification
     */
    addOrderBy(orderBy) {
    wasm.Pagination_add_order_by(this.ffiValue, orderBy.ffiValue);

        try {}

        finally {
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}