// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



/**
 * Direction for pagination
 */
export class PaginationDirection {
    #value = undefined;

    static #values = new Map([
        ["Forward", 0],
        ["Backward", 1]
    ]);

    static getAllEntries() {
        return PaginationDirection.#values.entries();
    }

    #internalConstructor(value) {
        if (arguments.length > 1 && arguments[0] === diplomatRuntime.internalConstructor) {
            // We pass in two internalConstructor arguments to create *new*
            // instances of this type, otherwise the enums are treated as singletons.
            if (arguments[1] === diplomatRuntime.internalConstructor ) {
                this.#value = arguments[2];
                return this;
            }
            return PaginationDirection.#objectValues[arguments[1]];
        }

        if (value instanceof PaginationDirection) {
            return value;
        }

        let intVal = PaginationDirection.#values.get(value);

        // Nullish check, checks for null or undefined
        if (intVal != null) {
            return PaginationDirection.#objectValues[intVal];
        }

        throw TypeError(value + " is not a PaginationDirection and does not correspond to any of its enumerator values.");
    }

    /** @internal */
    static fromValue(value) {
        return new PaginationDirection(value);
    }

    get value(){
        return [...PaginationDirection.#values.keys()][this.#value];
    }

    /** @internal */
    get ffiValue(){
        return this.#value;
    }
    static #objectValues = [
        new PaginationDirection(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 0),
        new PaginationDirection(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 1),
    ];

    static Forward = PaginationDirection.#objectValues[0];
    static Backward = PaginationDirection.#objectValues[1];


    constructor(value) {
        return this.#internalConstructor(...arguments)
    }
}