// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { OrderBy } from "./OrderBy"
import type { PaginationDirection } from "./PaginationDirection"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Pagination configuration for queries
 */
export class Pagination {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Creates a new Pagination with default values
     */
    static new_(): Pagination;

    /**
     * Sets the cursor for pagination
     */
    setCursor(cursor: string): void;

    /**
     * Sets the limit for pagination
     */
    setLimit(limit: number): void;

    /**
     * Sets the direction for pagination
     */
    setDirection(direction: PaginationDirection): void;

    /**
     * Adds an ordering specification
     */
    addOrderBy(orderBy: OrderBy): void;
}