// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Direction for pagination
 */
export class PaginationDirection {

    /** @internal */
    static fromValue(value: PaginationDirection | string): PaginationDirection;

    get value(): string;

    /** @internal */
    get ffiValue(): number;

    static Forward : PaginationDirection;
    static Backward : PaginationDirection;


    constructor(value: PaginationDirection | string );
}