// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



/**
 * Pattern matching mode for key queries
 */
export class PatternMatching {
    #value = undefined;

    static #values = new Map([
        ["FixedLen", 0],
        ["VariableLen", 1]
    ]);

    static getAllEntries() {
        return PatternMatching.#values.entries();
    }

    #internalConstructor(value) {
        if (arguments.length > 1 && arguments[0] === diplomatRuntime.internalConstructor) {
            // We pass in two internalConstructor arguments to create *new*
            // instances of this type, otherwise the enums are treated as singletons.
            if (arguments[1] === diplomatRuntime.internalConstructor ) {
                this.#value = arguments[2];
                return this;
            }
            return PatternMatching.#objectValues[arguments[1]];
        }

        if (value instanceof PatternMatching) {
            return value;
        }

        let intVal = PatternMatching.#values.get(value);

        // Nullish check, checks for null or undefined
        if (intVal != null) {
            return PatternMatching.#objectValues[intVal];
        }

        throw TypeError(value + " is not a PatternMatching and does not correspond to any of its enumerator values.");
    }

    /** @internal */
    static fromValue(value) {
        return new PatternMatching(value);
    }

    get value(){
        return [...PatternMatching.#values.keys()][this.#value];
    }

    /** @internal */
    get ffiValue(){
        return this.#value;
    }
    static #objectValues = [
        new PatternMatching(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 0),
        new PatternMatching(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 1),
    ];

    static FixedLen = PatternMatching.#objectValues[0];
    static VariableLen = PatternMatching.#objectValues[1];


    constructor(value) {
        return this.#internalConstructor(...arguments)
    }
}