// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Pattern matching mode for key queries
 */
export class PatternMatching {

    /** @internal */
    static fromValue(value: PatternMatching | string): PatternMatching;

    get value(): string;

    /** @internal */
    get ffiValue(): number;

    static FixedLen : PatternMatching;
    static VariableLen : PatternMatching;


    constructor(value: PatternMatching | string );
}