// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Represents player achievement progress
 */
export class PlayerAchievementEntry {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Gets the player address (hex)
     */
    playerAddress(): string;

    /**
     * Gets the total points
     */
    totalPoints(): number;

    /**
     * Gets the completed achievements count
     */
    completedAchievements(): number;

    /**
     * Gets the total achievements count
     */
    totalAchievements(): number;

    /**
     * Gets the completion percentage
     */
    completionPercentage(): number;

    /**
     * Gets the achievements count
     */
    achievementsCount(): number;

    /**
     * Gets the updated_at timestamp
     */
    updatedAt(): bigint;

    /**
     * Creates a player achievement entry from JSON
     */
    static fromJson(json: string): PlayerAchievementEntry;

    /**
     * Serializes the player achievement entry to JSON
     */
    toJson(): string;
}