// generated by diplomat-tool
import { DojoError } from "./DojoError.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const PlayerAchievementEntry_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.PlayerAchievementEntry_destroy(ptr);
});

/**
 * Represents player achievement progress
 */
export class PlayerAchievementEntry {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("PlayerAchievementEntry is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            PlayerAchievementEntry_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    /**
     * Gets the player address (hex)
     */
    playerAddress() {
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.PlayerAchievementEntry_player_address(this.ffiValue, write.buffer);

        try {
            return write.readString8();
        }

        finally {
            write.free();
        }
    }

    /**
     * Gets the total points
     */
    totalPoints() {

        const result = wasm.PlayerAchievementEntry_total_points(this.ffiValue);

        try {
            return result;
        }

        finally {
        }
    }

    /**
     * Gets the completed achievements count
     */
    completedAchievements() {

        const result = wasm.PlayerAchievementEntry_completed_achievements(this.ffiValue);

        try {
            return result;
        }

        finally {
        }
    }

    /**
     * Gets the total achievements count
     */
    totalAchievements() {

        const result = wasm.PlayerAchievementEntry_total_achievements(this.ffiValue);

        try {
            return result;
        }

        finally {
        }
    }

    /**
     * Gets the completion percentage
     */
    completionPercentage() {

        const result = wasm.PlayerAchievementEntry_completion_percentage(this.ffiValue);

        try {
            return result;
        }

        finally {
        }
    }

    /**
     * Gets the achievements count
     */
    achievementsCount() {

        const result = wasm.PlayerAchievementEntry_achievements_count(this.ffiValue);

        try {
            return result;
        }

        finally {
        }
    }

    /**
     * Gets the updated_at timestamp
     */
    updatedAt() {

        const result = wasm.PlayerAchievementEntry_updated_at(this.ffiValue);

        try {
            return result;
        }

        finally {
        }
    }

    /**
     * Creates a player achievement entry from JSON
     */
    static fromJson(json) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const jsonSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, json)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.PlayerAchievementEntry_from_json(diplomatReceive.buffer, jsonSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new DojoError(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
                throw new globalThis.Error('DojoError: ' + cause.toString(), { cause });
            }
            return new PlayerAchievementEntry(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * Serializes the player achievement entry to JSON
     */
    toJson() {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);

        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);


        const result = wasm.PlayerAchievementEntry_to_json(diplomatReceive.buffer, this.ffiValue, write.buffer);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new DojoError(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
                throw new globalThis.Error('DojoError: ' + cause.toString(), { cause });
            }
            return write.readString8();
        }

        finally {
            diplomatReceive.free();
            write.free();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}