// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Type of primitive
 */
export class PrimitiveType {

    /** @internal */
    static fromValue(value: PrimitiveType | string): PrimitiveType;

    get value(): string;

    /** @internal */
    get ffiValue(): number;

    static I8 : PrimitiveType;
    static I16 : PrimitiveType;
    static I32 : PrimitiveType;
    static I64 : PrimitiveType;
    static I128 : PrimitiveType;
    static U8 : PrimitiveType;
    static U16 : PrimitiveType;
    static U32 : PrimitiveType;
    static U64 : PrimitiveType;
    static U128 : PrimitiveType;
    static U256 : PrimitiveType;
    static Bool : PrimitiveType;
    static Felt252 : PrimitiveType;
    static ClassHash : PrimitiveType;
    static ContractAddress : PrimitiveType;
    static EthAddress : PrimitiveType;


    constructor(value: PrimitiveType | string );
}