// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { PrimitiveType } from "./PrimitiveType"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Represents a primitive Cairo type with its value
 */
export class Primitive {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Gets the primitive type
     */
    primitiveType(): PrimitiveType;

    /**
     * Creates a primitive from JSON
     */
    static fromJson(json: string): Primitive;

    /**
     * Serializes the primitive to JSON
     */
    toJson(): string;
}