// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * JSON-RPC provider for Starknet
 */
export class Provider {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Creates a new provider from an RPC URL
     */
    static new_(rpcUrl: string): Provider;

    /**
     * Gets the chain ID
     */
    chainId(): string;

    /**
     * Gets the latest block number
     */
    blockNumber(): bigint;
}