// generated by diplomat-tool
import { FieldElement } from "./FieldElement.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const Signature_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.Signature_destroy(ptr);
});

/**
 * Represents a signature (r, s pair)
 */
export class Signature {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("Signature is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            Signature_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    /**
     * Creates a new signature from r and s components
     */
    static new_(r, s) {

        const result = wasm.Signature_new(r.ffiValue, s.ffiValue);

        try {
            return new Signature(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
        }
    }

    /**
     * Gets the r component
     */
    r() {
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.Signature_r(this.ffiValue, write.buffer);

        try {
            return write.readString8();
        }

        finally {
            write.free();
        }
    }

    /**
     * Gets the s component
     */
    s() {
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.Signature_s(this.ffiValue, write.buffer);

        try {
            return write.readString8();
        }

        finally {
            write.free();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}