// generated by diplomat-tool
import type { FieldElement } from "./FieldElement"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Represents a signature (r, s pair)
 */
export class Signature {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Creates a new signature from r and s components
     */
    static new_(r: FieldElement, s: FieldElement): Signature;

    /**
     * Gets the r component
     */
    r(): string;

    /**
     * Gets the s component
     */
    s(): string;
}