// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Represents a Dojo struct
 */
export class Struct {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Gets the struct name
     */
    name(): string;

    /**
     * Gets the number of children (members)
     */
    childrenCount(): number;

    /**
     * Creates a new struct from JSON schema
     */
    static fromJson(json: string): Struct;

    /**
     * Serializes the struct to JSON
     */
    toJson(): string;
}