// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Represents a token contract
 */
export class TokenContract {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Gets the contract address (hex)
     */
    contractAddress(): string;

    /**
     * Gets the contract type as string
     */
    contractType(): string;

    /**
     * Creates a token contract from JSON
     */
    static fromJson(json: string): TokenContract;

    /**
     * Serializes the token contract to JSON
     */
    toJson(): string;
}