// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Represents a token (ERC20, ERC721, or ERC1155)
 */
export class Token {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Gets the contract address (hex)
     */
    contractAddress(): string;

    /**
     * Gets the token name
     */
    name(): string;

    /**
     * Gets the token symbol
     */
    symbol(): string;

    /**
     * Gets the token decimals
     */
    decimals(): number;

    /**
     * Gets the metadata as JSON string
     */
    metadata(): string;

    /**
     * Creates a token from JSON
     */
    static fromJson(json: string): Token;

    /**
     * Serializes the token to JSON
     */
    toJson(): string;
}