// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Represents a token balance for an account
 */
export class TokenBalance {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Gets the account address (hex)
     */
    accountAddress(): string;

    /**
     * Gets the contract address (hex)
     */
    contractAddress(): string;

    /**
     * Gets the balance as a string
     */
    balance(): string;

    /**
     * Creates a token balance from JSON
     */
    static fromJson(json: string): TokenBalance;

    /**
     * Serializes the token balance to JSON
     */
    toJson(): string;
}