// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Represents a token transfer event
 */
export class TokenTransfer {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Gets the from address (hex)
     */
    fromAddress(): string;

    /**
     * Gets the to address (hex)
     */
    toAddress(): string;

    /**
     * Gets the contract address (hex)
     */
    contractAddress(): string;

    /**
     * Gets the amount as a string
     */
    amount(): string;

    /**
     * Gets the executed_at timestamp
     */
    executedAt(): bigint;

    /**
     * Creates a token transfer from JSON
     */
    static fromJson(json: string): TokenTransfer;

    /**
     * Serializes the token transfer to JSON
     */
    toJson(): string;
}