// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { FieldElement } from "./FieldElement"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Opaque handle to a Torii client instance
 */
export class ToriiClient {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Creates a new Torii client instance
     */
    static new_(toriiUrl: string): ToriiClient;

    /**
     * Gets information about the Torii server
     */
    info(): string;

    /**
     * Publishes a message to the network
     */
    publishMessage(messageJson: string, signatureR: FieldElement, signatureS: FieldElement, worldAddress: FieldElement): string;
}