// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Represents a transaction
 */
export class Transaction {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Gets the transaction hash (hex)
     */
    transactionHash(): string;

    /**
     * Gets the sender address (hex)
     */
    senderAddress(): string;

    /**
     * Gets the max fee as string
     */
    maxFee(): string;

    /**
     * Gets the signature as JSON array string
     */
    signature(): string;

    /**
     * Gets the nonce as string
     */
    nonce(): string;

    /**
     * Gets the block timestamp
     */
    blockTimestamp(): bigint;

    /**
     * Gets the block number
     */
    blockNumber(): bigint;

    /**
     * Creates a transaction from JSON
     */
    static fromJson(json: string): Transaction;

    /**
     * Serializes the transaction to JSON
     */
    toJson(): string;
}