// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Represents a typed data structure for EIP-712 style signing
 */
export class TypedData {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Creates a new TypedData from JSON string
     */
    static newFromJson(json: string): TypedData;
}