// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Represents a 256-bit unsigned integer
 */
export class U256 {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Creates a new U256 from a hexadecimal string
     */
    static newFromHex(hex: string): U256;

    /**
     * Creates a new U256 from big-endian bytes
     */
    static newFromBytes(bytes: Array<number>): U256;

    /**
     * Returns the U256 as a hexadecimal string
     */
    toHex(): string;

    /**
     * Returns the U256 as bytes (big-endian)
     */
    toBytes(result: Array<number>): void;
}