// generated by diplomat-tool
import { DojoError } from "./DojoError.mjs"
import { FieldElement } from "./FieldElement.mjs"
import { Signature } from "./Signature.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const VerifyingKey_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.VerifyingKey_destroy(ptr);
});

/**
 * Represents a verifying key for signature verification
 */
export class VerifyingKey {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("VerifyingKey is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            VerifyingKey_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    /**
     * Returns the scalar value of the verifying key
     */
    scalar() {
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.VerifyingKey_scalar(this.ffiValue, write.buffer);

        try {
            return write.readString8();
        }

        finally {
            write.free();
        }
    }

    /**
     * Verifies a signature
     */
    verify(hash, signature) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 1, true);


        const result = wasm.VerifyingKey_verify(diplomatReceive.buffer, this.ffiValue, hash.ffiValue, signature.ffiValue);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new DojoError(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
                throw new globalThis.Error('DojoError: ' + cause.toString(), { cause });
            }
            return (new Uint8Array(wasm.memory.buffer, diplomatReceive.buffer, 1))[0] === 1;
        }

        finally {
            diplomatReceive.free();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}