// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { FieldElement } from "./FieldElement"
import type { Signature } from "./Signature"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Represents a verifying key for signature verification
 */
export class VerifyingKey {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Returns the scalar value of the verifying key
     */
    scalar(): string;

    /**
     * Verifies a signature
     */
    verify(hash: FieldElement, signature: Signature): boolean;
}