// generated by diplomat-tool
import type { DojoError } from "./DojoError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Represents a Dojo world
 */
export class World {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Gets the world address (hex)
     */
    worldAddress(): string;

    /**
     * Gets the number of models in this world
     */
    modelsCount(): number;

    /**
     * Creates a new world from JSON
     */
    static fromJson(json: string): World;

    /**
     * Serializes the world to JSON
     */
    toJson(): string;
}