// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!
#pragma once
#include <jsi/jsi.h>
#include <iostream>
#include <map>
#include <memory>
#include <ReactCommon/CallInvoker.h>
#include "UniffiCallInvoker.h"

namespace react = facebook::react;
namespace jsi = facebook::jsi;

class NativeDojo : public jsi::HostObject {
  private:
    // For calling back into JS from Rust.
    std::shared_ptr<uniffi_runtime::UniffiCallInvoker> callInvoker;

  protected:
    std::map<std::string,jsi::Value> props;
    jsi::Value cpp_uniffi_internal_fn_func_ffi__string_to_byte_length(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_internal_fn_func_ffi__string_to_arraybuffer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_internal_fn_func_ffi__arraybuffer_to_string(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_clone_toriiclient(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_free_toriiclient(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_constructor_toriiclient_new(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_constructor_toriiclient_new_with_config(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_method_toriiclient_achievements(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_method_toriiclient_activities(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_method_toriiclient_aggregations(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_method_toriiclient_cancel_subscription(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_method_toriiclient_contracts(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_method_toriiclient_controllers(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_method_toriiclient_entities(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_method_toriiclient_event_messages(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_method_toriiclient_player_achievements(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_method_toriiclient_publish_message(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_method_toriiclient_publish_message_batch(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_method_toriiclient_sql(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_method_toriiclient_starknet_events(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_method_toriiclient_subscribe_entity_updates(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_method_toriiclient_subscribe_event_updates(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_method_toriiclient_subscribe_token_balance_updates(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_method_toriiclient_subscribe_token_updates(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_method_toriiclient_subscribe_transaction_updates(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_method_toriiclient_token_balances(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_method_toriiclient_token_contracts(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_method_toriiclient_token_transfers(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_method_toriiclient_tokens(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_method_toriiclient_transactions(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_method_toriiclient_worlds(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_init_callback_vtable_entityupdatecallback(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_init_callback_vtable_eventupdatecallback(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_init_callback_vtable_tokenbalanceupdatecallback(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_init_callback_vtable_tokenupdatecallback(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_fn_init_callback_vtable_transactionupdatecallback(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_toriiclient_achievements(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_toriiclient_activities(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_toriiclient_aggregations(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_toriiclient_cancel_subscription(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_toriiclient_contracts(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_toriiclient_controllers(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_toriiclient_entities(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_toriiclient_event_messages(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_toriiclient_player_achievements(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_toriiclient_publish_message(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_toriiclient_publish_message_batch(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_toriiclient_sql(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_toriiclient_starknet_events(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_toriiclient_subscribe_entity_updates(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_toriiclient_subscribe_event_updates(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_toriiclient_subscribe_token_balance_updates(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_toriiclient_subscribe_token_updates(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_toriiclient_subscribe_transaction_updates(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_toriiclient_token_balances(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_toriiclient_token_contracts(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_toriiclient_token_transfers(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_toriiclient_tokens(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_toriiclient_transactions(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_toriiclient_worlds(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_constructor_toriiclient_new(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_constructor_toriiclient_new_with_config(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_entityupdatecallback_on_update(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_entityupdatecallback_on_error(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_eventupdatecallback_on_update(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_eventupdatecallback_on_error(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_tokenbalanceupdatecallback_on_update(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_tokenbalanceupdatecallback_on_error(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_tokenupdatecallback_on_update(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_tokenupdatecallback_on_error(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_transactionupdatecallback_on_update(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_dojo_uniffi_checksum_method_transactionupdatecallback_on_error(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_ffi_dojo_uniffi_uniffi_contract_version(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_ffi_ToriiClient__bless_pointer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);

  public:
    NativeDojo(jsi::Runtime &rt, std::shared_ptr<uniffi_runtime::UniffiCallInvoker> callInvoker);
    virtual ~NativeDojo();

    /**
     * The entry point into the crate.
     *
     * React Native must call `NativeDojo.registerModule(rt, callInvoker)` before using
     * the Javascript interface.
     */
    static void registerModule(jsi::Runtime &rt, std::shared_ptr<react::CallInvoker> callInvoker);

    /**
     * Some cleanup into the crate goes here.
     *
     * Current implementation is empty, however, this is not guaranteed to always be the case.
     *
     * Clients should call `NativeDojo.unregisterModule(rt)` after final use where possible.
     */
    static void unregisterModule(jsi::Runtime &rt);

    virtual jsi::Value get(jsi::Runtime& rt, const jsi::PropNameID& name);
    virtual void set(jsi::Runtime& rt,const jsi::PropNameID& name,const jsi::Value& value);
    virtual std::vector<jsi::PropNameID> getPropertyNames(jsi::Runtime& rt);
};